---
tag_list:
  - list
  - discussion
  - guide
  - gallery
  - meta
  - debug
text_color: rgb(235, 228, 221)
background_color: rgb(54, 59, 62)
favicon: default.ico
font: 'basic'
font_size: 7px
home_url: /
title: Madelyn O's Page
zone_name: open eyed
index_name: Madelyn O's Home
real_name: Madelyn O
user_name: mooasis
status_updated: "[NULL]"
status_emote: tongue.png
status_text: you just ate one of grandpa's famous buckets of garlic shrimp stew and your breath smells gnarlier than an unlabeled container in the back of the fridge!
---