---
tag_list:
  - list
  - discussion
  - guide
  - gallery
  - meta
  - debug
text_color: rgb(235, 228, 221)
background_color: rgb(54, 59, 62)
favicon: default.ico
font: 'basic'
font-size: 7px
title: epic website
zone_name: uuhh umm
index_name: home
---