---
tag_list:
  - list
  - discussion
  - guide
  - gallery
  - meta
  - debug
text_color: rgb(235, 228, 221)
background_color: rgb(54, 59, 62)
favicon: default.ico
font: 'basic'
font_size: 7px
home_url: /
info_url: https://github.com/mooasis/mooasis.github.io
title: Madelyn O's Page
zone_name: open eyed
index_name: Madelyn O's Home
real_name: Madelyn O
user_name: mooasis
status_updated: "[NULL]"
status_emote: grin.png
status_text: at the end of time we all return to the primordial iggy
---