---
tag_list:
  - list
  - discussion
  - guide
  - gallery
  - meta
  - debug
text_color: rgb(235, 228, 221)
background_color: rgb(54, 59, 62)
favicon: default.ico
font: 'basic'
font-size: 7px
title: Madelyn O's Page
zone_name: open eyed
index_name: Madelyn O's Home
---